import { INSTRUCTIONAL_ACTIONS, type InstructionalStep } from "@/features/learning/lib/instructional-actions";
import { shuffleQuestionOptions, type CodeEvaluatorId, type QuestionItem } from "@/features/learning/lib/question-bank";

export type StageSpec = {
  id: string; label: string; title: string; intro: string; code: string;
  evaluatorId: CodeEvaluatorId; constructionPrompt: string; starterCode: string; solution: string;
  completion: { prompt: string; options: string[]; correct: string };
  concept: string; result: string; boundary: string;
};

export type AdditionalTask = {
  id: "cnn" | "regression"; eyebrow: string; title: string; description: string; stages: StageSpec[];
};

const cnnStages: StageSpec[] = [
  { id: "load_images", label: "Load images", title: "Load real handwritten-digit images", intro: "Reshape all 5,620 UCI Optical Digits records into labeled 8 × 8 PyTorch image tensors.", code: "images = df[pixel_columns].to_numpy(dtype='float32').reshape(-1, 1, 8, 8)\ndataset = TensorDataset(torch.from_numpy(images), torch.from_numpy(labels))", evaluatorId: "cnn_load_images", constructionPrompt: "Convert the 64 intensity columns into 8 × 8 image tensors and create a TensorDataset.", starterCode: "import torch\nfrom torch.utils.data import TensorDataset\n", solution: "dataset = TensorDataset(torch.from_numpy(images), torch.from_numpy(labels))", completion: { prompt: "Why reshape each record to 1 × 8 × 8?", options: ["To represent channel, height, and width for Conv2d", "To create 64 images", "To remove its label"], correct: "To represent channel, height, and width for Conv2d" }, concept: "image tensors", result: "a PyTorch image dataset", boundary: "Reshaping does not train the CNN" },
  { id: "normalize_split", label: "Normalize & split", title: "Create training and test loaders", intro: "Reserve 20% of the real digit images for testing and normalize their 0–16 intensities during training.", code: "train_dataset, test_dataset = random_split(dataset, [train_size, test_size], generator=generator)", evaluatorId: "cnn_normalize", constructionPrompt: "Split the TensorDataset reproducibly and build DataLoaders.", starterCode: "from torch.utils.data import DataLoader, random_split\n", solution: "train_dataset, test_dataset = random_split(dataset, [train_size, test_size], generator=generator)", completion: { prompt: "Why keep the test subset separate?", options: ["To evaluate images not used for updates", "To increase resolution", "To invent labels"], correct: "To evaluate images not used for updates" }, concept: "held-out evaluation", result: "training and test loaders", boundary: "Test images do not update weights" },
  { id: "build_cnn", label: "Build CNN", title: "Build convolutional feature extractors", intro: "Combine PyTorch convolution, activation, pooling, flattening, and a ten-class output layer.", code: "model = nn.Sequential(nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2), nn.Flatten(), nn.Linear(256, 10))", evaluatorId: "cnn_build", constructionPrompt: "Create a PyTorch CNN with Conv2d, ReLU, pooling, flattening, and a ten-class output.", starterCode: "import torch\nfrom torch import nn\n", solution: "model = nn.Sequential(nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2), nn.Flatten(), nn.Linear(256, 10))", completion: { prompt: "Which layer learns local visual filters?", options: ["nn.Conv2d", "nn.Flatten", "DataLoader"], correct: "nn.Conv2d" }, concept: "convolutional layers", result: "an untrained PyTorch CNN", boundary: "Defining layers does not fit weights" },
  { id: "train_network", label: "Train network", title: "Optimize CNN weights", intro: "Use cross-entropy, backpropagation, and Adam updates over labeled image batches.", code: "optimizer.zero_grad()\nloss = loss_fn(model(images_batch / 16.0), labels_batch)\nloss.backward()\noptimizer.step()", evaluatorId: "cnn_train", constructionPrompt: "Run a PyTorch optimization step using backward and optimizer.step.", starterCode: "# Run one optimization step\n", solution: "optimizer.zero_grad()\nloss.backward()\noptimizer.step()", completion: { prompt: "Which call calculates gradients?", options: ["loss.backward()", "optimizer.zero_grad()", "model.eval()"], correct: "loss.backward()" }, concept: "backpropagation", result: "a trained CNN", boundary: "Training excludes test labels" },
  { id: "classify_images", label: "Classify", title: "Classify unseen digits", intro: "Run held-out tensors through the trained CNN without recording gradients and choose the largest class score.", code: "with torch.no_grad():\n    predictions = model(images_batch / 16.0).argmax(dim=1)", evaluatorId: "cnn_predict", constructionPrompt: "Predict digit classes in evaluation mode using torch.no_grad and argmax.", starterCode: "model.eval()\n", solution: "with torch.no_grad():\n    predictions = model(images_batch / 16.0).argmax(dim=1)", completion: { prompt: "Why use torch.no_grad()?", options: ["Inference does not need gradient history", "It adds images", "It changes labels"], correct: "Inference does not need gradient history" }, concept: "inference", result: "predicted digit classes", boundary: "Prediction does not update weights" },
  { id: "evaluate_cnn", label: "Evaluate", title: "Measure held-out accuracy", intro: "Compare predicted digit classes with unseen labels to measure classification accuracy.", code: "accuracy = (y_pred == y_test).float().mean().item()", evaluatorId: "cnn_evaluate", constructionPrompt: "Calculate the fraction of PyTorch predictions matching held-out labels.", starterCode: "# Measure test accuracy\n", solution: "accuracy = (y_pred == y_test).float().mean().item()", completion: { prompt: "What does test accuracy measure?", options: ["The fraction of held-out digits classified correctly", "Optimizer updates", "Average intensity"], correct: "The fraction of held-out digits classified correctly" }, concept: "classification accuracy", result: "test accuracy", boundary: "Evaluation does not retrain" },
];

const regressionStages: StageSpec[] = [
  { id: "prepare_housing_data", label: "Prepare data", title: "Load and clean housing records", intro: "Load property features and remove rows without a usable target price.", code: "df = pd.read_csv('houses.csv')\ndf = df.dropna(subset=['price'])", evaluatorId: "reg_load_data", constructionPrompt: "Load houses.csv into df and remove rows whose price is missing.", starterCode: "import pandas as pd\n\n# Load and clean the housing data\n", solution: "df = pd.read_csv('houses.csv')\ndf = df.dropna(subset=['price'])", completion: { prompt: "Which column is the regression target?", options: ["price", "bedrooms", "zipcode"], correct: "price" }, concept: "tabular records", result: "clean labeled rows", boundary: "Cleaning data does not fit a regression model" },
  { id: "split_housing_data", label: "Split data", title: "Reserve unseen houses", intro: "Separate feature rows and prices into training and test partitions.", code: "X_train, X_test, y_train, y_test = train_test_split(\n  X, y, test_size=0.2, random_state=42\n)", evaluatorId: "reg_split", constructionPrompt: "Split X and y into four train/test variables using a 20% test set.", starterCode: "from sklearn.model_selection import train_test_split\n\n# Split features and prices\n", solution: "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)", completion: { prompt: "With 500 houses and test_size=0.2, how many are held out?", options: ["100", "250", "400"], correct: "100" }, concept: "collection partitioning", result: "training and test sets", boundary: "Test prices remain unseen during fitting" },
  { id: "scale_features", label: "Scale features", title: "Put numeric features on comparable scales", intro: "Fit scaling statistics on training features and reuse them on test features.", code: "scaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)", evaluatorId: "reg_scale", constructionPrompt: "Create scaler, fit-transform X_train, and transform X_test into the two named scaled variables.", starterCode: "from sklearn.preprocessing import StandardScaler\n\n# Scale without test leakage\n", solution: "scaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)", completion: { prompt: "Which data should fit the scaler?", options: ["X_train", "X_test", "All houses before splitting"], correct: "X_train" }, concept: "reusable transformation", result: "scaled feature matrices", boundary: "Fit preprocessing only on training data" },
  { id: "train_regression", label: "Train model", title: "Fit a price model", intro: "Learn coefficients connecting housing features to continuous prices.", code: "model = LinearRegression()\nmodel.fit(X_train_scaled, y_train)", evaluatorId: "reg_train", constructionPrompt: "Create a LinearRegression model and fit it with X_train_scaled and y_train.", starterCode: "from sklearn.linear_model import LinearRegression\n\n# Train the price model\n", solution: "model = LinearRegression()\nmodel.fit(X_train_scaled, y_train)", completion: { prompt: "Which method learns regression coefficients?", options: ["model.fit", "model.predict", "mean_absolute_error"], correct: "model.fit" }, concept: "parameter fitting", result: "a fitted regression model", boundary: "Regression predicts a number, not a class label" },
  { id: "predict_prices", label: "Predict price", title: "Predict unseen house prices", intro: "Use the fitted model to estimate a continuous price for every test row.", code: "y_pred = model.predict(X_test_scaled)", evaluatorId: "reg_predict", constructionPrompt: "Predict prices from X_test_scaled and assign them to y_pred.", starterCode: "# Predict held-out prices\n", solution: "y_pred = model.predict(X_test_scaled)", completion: { prompt: "What does y_pred contain?", options: ["Predicted prices", "Training rows", "Feature names"], correct: "Predicted prices" }, concept: "function application", result: "continuous predictions", boundary: "Prediction does not use y_test as input" },
  { id: "evaluate_regression", label: "Measure error", title: "Measure prediction error", intro: "Compare predicted prices with held-out prices using an interpretable error metric.", code: "mae = mean_absolute_error(y_test, y_pred)", evaluatorId: "reg_evaluate", constructionPrompt: "Compute mean absolute error from y_test and y_pred and assign it to mae.", starterCode: "from sklearn.metrics import mean_absolute_error\n\n# Measure price error\n", solution: "mae = mean_absolute_error(y_test, y_pred)", completion: { prompt: "What does a lower MAE indicate?", options: ["Predictions are closer to true prices", "More classes were created", "The test set is larger"], correct: "Predictions are closer to true prices" }, concept: "output assertions", result: "mean absolute error", boundary: "Evaluation measures error without retraining" },
];

export const additionalTasks: Record<"cnn" | "regression", AdditionalTask> = {
  cnn: { id: "cnn", eyebrow: "Intermediate · Image classification", title: "Image Classification with CNNs", description: "Learn how pixels become features and how a convolutional neural network learns visual patterns.", stages: cnnStages },
  regression: { id: "regression", eyebrow: "Foundation · Regression", title: "House Price Regression", description: "Predict a continuous value from property features and measure how close predictions are.", stages: regressionStages },
};

function questions(task: AdditionalTask, stage: StageSpec, step: InstructionalStep): QuestionItem[] {
  const base = `${task.id}.${stage.id}.${step}`;
  const make = (index: number, typeLabel: string, prompt: string, options: string[], correctAnswer: string): QuestionItem => {
    const id = `${base}.${index}`;
    return { id, step, actionType: INSTRUCTIONAL_ACTIONS[step][index], typeLabel, prompt, options: shuffleQuestionOptions(id, options), correctAnswer, explanation: `The key idea is ${correctAnswer}.`, misconception: `${stage.id}_${step}`, learningObjectives: [`${task.id}_${stage.id}`] };
  };
  if (step === "implement") return [
    { ...make(2, "Code construction", stage.constructionPrompt, [], stage.solution), answerType: "code", evaluatorId: stage.evaluatorId, starterCode: stage.starterCode },
    make(0, "Code completion", stage.completion.prompt, stage.completion.options, stage.completion.correct),
    make(1, "Code debugging", `Which correction is valid for ${stage.label.toLowerCase()}?`, stage.completion.options, stage.completion.correct),
  ];
  const content: Record<Exclude<InstructionalStep, "implement">, [string, string[], string][]> = {
    activate: [[`Which familiar idea connects to this stage?`, [stage.concept, "A metric calculated before any outputs exist", "A transformation fitted on held-out examples"], stage.concept], [`What does this stage produce?`, [stage.result, "A final metric with no predictions", "A second copy of the unprocessed inputs"], stage.result], [`Which description fits ${stage.label.toLowerCase()}?`, [stage.intro, "It combines fitting and evaluation on the same examples", "It changes labels to match the model's outputs"], stage.intro]],
    connect: [[`Match ${stage.concept} to its ML result.`, [stage.result, "A test label used as an input feature", "A metric that updates model weights"], stage.result], [`Which relationship is correct?`, [`${stage.concept} becomes ${stage.result}`, "The test partition should influence every fitted transformation", "Labels are optional whenever inputs are numeric"], `${stage.concept} becomes ${stage.result}`], [`Which analogy transfers best?`, [`A program transforms input into output`, "A unit test rewrites a method until it passes", "A method learns from the expected output supplied at inference time"], "A program transforms input into output"]],
    learn: [[`What transfers into this stage?`, [stage.concept, "A final score computed before evaluation", "Statistics learned from the test partition"], stage.concept], [`What is newly produced?`, [stage.result, "The held-out targets used as model inputs", "A fitted preprocessing step with test-set statistics"], stage.result], [`Which boundary is correct?`, [stage.boundary, "Test examples may update preprocessing statistics but not model weights", "Every pipeline operation estimates trainable parameters"], stage.boundary]],
    practice: [[`Which statement corrects a likely misconception?`, [stage.boundary, "Data leakage is harmless when test labels are not read directly", "Prediction may update weights if the model is confident"], stage.boundary], [stage.completion.prompt, stage.completion.options, stage.completion.correct], [`Where does ${stage.label.toLowerCase()} belong?`, [`Before the next pipeline stage`, "After evaluation so the result cannot affect the metric", "In both training and test branches with independent fitting"], "Before the next pipeline stage"]],
    review: [[`Which result summarizes this stage?`, [stage.result, "A training metric treated as held-out performance", "A transformed target used as an input feature"], stage.result], [`Would the same principle transfer to another dataset?`, ["Yes, with task-appropriate inputs", "Only when the new dataset has identical feature values", "Only if the held-out set is included during fitting"], "Yes, with task-appropriate inputs"], [`Which boundary must remain true?`, [stage.boundary, "Test data can guide fitting if final evaluation uses a different metric", "Evaluation is optional when training loss is low"], stage.boundary]],
  };
  const labels: Record<Exclude<InstructionalStep, "implement">, string[]> = { activate: ["Concept identification", "Output prediction", "Code explanation"], connect: ["Concept matching", "Comparison", "Analogy mapping"], learn: ["Transfer or new", "Difference", "Concept boundary"], practice: ["Misconception check", "Find the issue", "Pipeline ordering"], review: ["Concept summary", "New scenario", "Final checkpoint"] };
  return content[step].map(([prompt, options, answer], index) => make(index, labels[step][index], prompt, options, answer));
}

export function additionalQuestionBank(task: AdditionalTask, stage: StageSpec): Record<InstructionalStep, QuestionItem[]> {
  return Object.fromEntries((["activate", "connect", "implement", "learn", "practice", "review"] as InstructionalStep[]).map((step) => [step, questions(task, stage, step)])) as Record<InstructionalStep, QuestionItem[]>;
}
