import { INSTRUCTIONAL_ACTIONS, type InstructionalStep } from "./instructional-actions";
import type { CodeEvaluatorId, QuestionItem } from "./question-bank";

export type StageSpec = {
  id: string; label: string; title: string; intro: string; code: string;
  evaluatorId: CodeEvaluatorId; constructionPrompt: string; starterCode: string; solution: string;
  completion: { prompt: string; options: string[]; correct: string };
  concept: string; result: string; boundary: string;
};

export type AdditionalTask = {
  id: "cnn" | "regression"; eyebrow: string; title: string; description: string; stages: StageSpec[];
};

const cnnStages: StageSpec[] = [
  { id: "load_images", label: "Load images", title: "Load labeled image data", intro: "Load images and labels while preserving the relationship between every image and its class.", code: "train_ds = image_dataset_from_directory(\n    'images', image_size=(128, 128)\n)", evaluatorId: "cnn_load_images", constructionPrompt: "Load images from the images directory at 128 × 128 pixels and assign the dataset to train_ds.", starterCode: "from tensorflow.keras.utils import image_dataset_from_directory\n\n# Load the image dataset\n", solution: "train_ds = image_dataset_from_directory('images', image_size=(128, 128))", completion: { prompt: "Which function loads labeled folders of images?", options: ["image_dataset_from_directory", "model.fit", "mean_squared_error"], correct: "image_dataset_from_directory" }, concept: "labeled examples", result: "an image dataset", boundary: "Loading images does not train the CNN" },
  { id: "normalize_split", label: "Normalize & split", title: "Prepare pixels for learning", intro: "Scale pixel values and reserve validation images that the optimizer does not train on.", code: "normalizer = Rescaling(1./255)\ntrain_ds = train_ds.map(lambda x, y: (normalizer(x), y))", evaluatorId: "cnn_normalize", constructionPrompt: "Create a Keras Rescaling layer that maps pixel values into the 0–1 range and assign it to normalizer.", starterCode: "from tensorflow.keras.layers import Rescaling\n\n# Scale pixels to 0–1\n", solution: "normalizer = Rescaling(1./255)", completion: { prompt: "Complete the scale factor: Rescaling(____)", options: ["1./255", "255", "0"], correct: "1./255" }, concept: "numeric normalization", result: "scaled pixels", boundary: "Validation images must not update model weights" },
  { id: "build_cnn", label: "Build CNN", title: "Build convolutional feature extractors", intro: "Combine convolution, pooling, and dense layers into a classifier.", code: "model = Sequential([\n  Conv2D(32, 3, activation='relu'),\n  MaxPooling2D(), Flatten(), Dense(3)\n])", evaluatorId: "cnn_build", constructionPrompt: "Create a Sequential model named model containing a Conv2D layer followed by MaxPooling2D.", starterCode: "from tensorflow.keras import Sequential\nfrom tensorflow.keras.layers import Conv2D, MaxPooling2D\n\n# Build the CNN\n", solution: "model = Sequential([Conv2D(32, 3, activation='relu'), MaxPooling2D()])", completion: { prompt: "Which layer learns local visual filters?", options: ["Conv2D", "Rescaling", "accuracy_score"], correct: "Conv2D" }, concept: "composed objects", result: "an untrained CNN", boundary: "Defining layers does not fit their weights" },
  { id: "train_network", label: "Train network", title: "Optimize CNN weights", intro: "Compile the network and update its parameters from labeled training batches.", code: "model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')\nhistory = model.fit(train_ds, epochs=5)", evaluatorId: "cnn_train", constructionPrompt: "Train model on train_ds for 5 epochs and assign the returned history to history.", starterCode: "# Train the compiled CNN\n", solution: "history = model.fit(train_ds, epochs=5)", completion: { prompt: "Which method updates the CNN weights?", options: ["model.fit", "model.predict", "model.evaluate"], correct: "model.fit" }, concept: "iterative parameter updates", result: "a trained CNN", boundary: "Training uses train_ds, not the held-out test labels" },
  { id: "classify_images", label: "Classify", title: "Classify unseen images", intro: "Apply the trained CNN to held-out image batches.", code: "probabilities = model.predict(test_ds)\npredictions = probabilities.argmax(axis=1)", evaluatorId: "cnn_predict", constructionPrompt: "Use model to predict test_ds and assign the output probabilities to probabilities.", starterCode: "# Predict held-out images\n", solution: "probabilities = model.predict(test_ds)", completion: { prompt: "Which call produces outputs for test images?", options: ["model.predict(test_ds)", "model.fit(test_ds)", "test_ds.compile()"], correct: "model.predict(test_ds)" }, concept: "method application", result: "class probabilities", boundary: "Prediction uses weights without updating them" },
  { id: "evaluate_cnn", label: "Evaluate", title: "Measure classification performance", intro: "Evaluate the trained network on held-out images and inspect its errors.", code: "test_loss, test_accuracy = model.evaluate(test_ds)", evaluatorId: "cnn_evaluate", constructionPrompt: "Evaluate model on test_ds and assign the two returned values to test_loss and test_accuracy.", starterCode: "# Evaluate held-out images\n", solution: "test_loss, test_accuracy = model.evaluate(test_ds)", completion: { prompt: "Which method evaluates a Keras model?", options: ["model.evaluate", "model.fit", "model.add"], correct: "model.evaluate" }, concept: "expected-versus-actual testing", result: "test loss and accuracy", boundary: "Evaluation must use held-out images" },
];

const regressionStages: StageSpec[] = [
  { id: "prepare_housing_data", label: "Prepare data", title: "Load and clean housing records", intro: "Load property features and remove rows without a usable target price.", code: "df = pd.read_csv('houses.csv')\ndf = df.dropna(subset=['price'])", evaluatorId: "reg_load_data", constructionPrompt: "Load houses.csv into df and remove rows whose price is missing.", starterCode: "import pandas as pd\n\n# Load and clean the housing data\n", solution: "df = pd.read_csv('houses.csv')\ndf = df.dropna(subset=['price'])", completion: { prompt: "Which column is the regression target?", options: ["price", "bedrooms", "zipcode"], correct: "price" }, concept: "tabular records", result: "clean labeled rows", boundary: "Cleaning data does not fit a regression model" },
  { id: "split_housing_data", label: "Split data", title: "Reserve unseen houses", intro: "Separate feature rows and prices into training and test partitions.", code: "X_train, X_test, y_train, y_test = train_test_split(\n  X, y, test_size=0.2, random_state=42\n)", evaluatorId: "reg_split", constructionPrompt: "Split X and y into four train/test variables using a 20% test set.", starterCode: "from sklearn.model_selection import train_test_split\n\n# Split features and prices\n", solution: "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)", completion: { prompt: "With 500 houses and test_size=0.2, how many are held out?", options: ["100", "250", "400"], correct: "100" }, concept: "collection partitioning", result: "training and test sets", boundary: "Test prices remain unseen during fitting" },
  { id: "scale_features", label: "Scale features", title: "Put numeric features on comparable scales", intro: "Fit scaling statistics on training features and reuse them on test features.", code: "scaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)", evaluatorId: "reg_scale", constructionPrompt: "Create scaler, fit-transform X_train, and transform X_test into the two named scaled variables.", starterCode: "from sklearn.preprocessing import StandardScaler\n\n# Scale without test leakage\n", solution: "scaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)", completion: { prompt: "Which data should fit the scaler?", options: ["X_train", "X_test", "All houses before splitting"], correct: "X_train" }, concept: "reusable transformation", result: "scaled feature matrices", boundary: "Fit preprocessing only on training data" },
  { id: "train_regression", label: "Train model", title: "Fit a price model", intro: "Learn coefficients connecting housing features to continuous prices.", code: "model = LinearRegression()\nmodel.fit(X_train_scaled, y_train)", evaluatorId: "reg_train", constructionPrompt: "Create a LinearRegression model and fit it with X_train_scaled and y_train.", starterCode: "from sklearn.linear_model import LinearRegression\n\n# Train the price model\n", solution: "model = LinearRegression()\nmodel.fit(X_train_scaled, y_train)", completion: { prompt: "Which method learns regression coefficients?", options: ["model.fit", "model.predict", "mean_absolute_error"], correct: "model.fit" }, concept: "parameter fitting", result: "a fitted regression model", boundary: "Regression predicts a number, not a class label" },
  { id: "predict_prices", label: "Predict price", title: "Predict unseen house prices", intro: "Use the fitted model to estimate a continuous price for every test row.", code: "y_pred = model.predict(X_test_scaled)", evaluatorId: "reg_predict", constructionPrompt: "Predict prices from X_test_scaled and assign them to y_pred.", starterCode: "# Predict held-out prices\n", solution: "y_pred = model.predict(X_test_scaled)", completion: { prompt: "What does y_pred contain?", options: ["Predicted prices", "Training rows", "Feature names"], correct: "Predicted prices" }, concept: "function application", result: "continuous predictions", boundary: "Prediction does not use y_test as input" },
  { id: "evaluate_regression", label: "Measure error", title: "Measure prediction error", intro: "Compare predicted prices with held-out prices using an interpretable error metric.", code: "mae = mean_absolute_error(y_test, y_pred)", evaluatorId: "reg_evaluate", constructionPrompt: "Compute mean absolute error from y_test and y_pred and assign it to mae.", starterCode: "from sklearn.metrics import mean_absolute_error\n\n# Measure price error\n", solution: "mae = mean_absolute_error(y_test, y_pred)", completion: { prompt: "What does a lower MAE indicate?", options: ["Predictions are closer to true prices", "More classes were created", "The test set is larger"], correct: "Predictions are closer to true prices" }, concept: "output assertions", result: "mean absolute error", boundary: "Evaluation measures error without retraining" },
];

export const additionalTasks: Record<"cnn" | "regression", AdditionalTask> = {
  cnn: { id: "cnn", eyebrow: "Intermediate · Image classification", title: "Image Classification with CNNs", description: "Learn how pixels become features and how a convolutional neural network learns visual patterns.", stages: cnnStages },
  regression: { id: "regression", eyebrow: "Foundation · Regression", title: "House Price Regression", description: "Predict a continuous value from property features and measure how close predictions are.", stages: regressionStages },
};

function questions(task: AdditionalTask, stage: StageSpec, step: InstructionalStep): QuestionItem[] {
  const base = `${task.id}.${stage.id}.${step}`;
  const make = (index: number, typeLabel: string, prompt: string, options: string[], correctAnswer: string): QuestionItem => ({ id: `${base}.${index}`, step, actionType: INSTRUCTIONAL_ACTIONS[step][index], typeLabel, prompt, options, correctAnswer, explanation: `The key idea is ${correctAnswer}.`, misconception: `${stage.id}_${step}`, learningObjectives: [`${task.id}_${stage.id}`] });
  if (step === "implement") return [
    { ...make(2, "Code construction", stage.constructionPrompt, [], stage.solution), answerType: "code", evaluatorId: stage.evaluatorId, starterCode: stage.starterCode },
    make(0, "Code completion", stage.completion.prompt, stage.completion.options, stage.completion.correct),
    make(1, "Code debugging", `Which correction is valid for ${stage.label.toLowerCase()}?`, stage.completion.options, stage.completion.correct),
  ];
  const content: Record<Exclude<InstructionalStep, "implement">, [string, string[], string][]> = {
    activate: [[`Which familiar idea connects to this stage?`, [stage.concept, "UI styling", "Password hashing"], stage.concept], [`What does this stage produce?`, [stage.result, "A login session", "A web route"], stage.result], [`Which description fits ${stage.label.toLowerCase()}?`, [stage.intro, "It skips data preparation", "It changes the user's account"], stage.intro]],
    connect: [[`Match ${stage.concept} to its ML result.`, [stage.result, "A CSS rule", "An access token"], stage.result], [`Which relationship is correct?`, [`${stage.concept} becomes ${stage.result}`, "Training and testing are identical", "Labels are unnecessary"], `${stage.concept} becomes ${stage.result}`], [`Which analogy transfers best?`, [`A program transforms input into output`, "A color changes a password", "A route trains a model"], "A program transforms input into output"]],
    learn: [[`What transfers into this stage?`, [stage.concept, "The final score", "A page title"], stage.concept], [`What is newly produced?`, [stage.result, "An email address", "A navigation event"], stage.result], [`Which boundary is correct?`, [stage.boundary, "Training and testing should share answers", "Every operation trains the model"], stage.boundary]],
    practice: [[`Which statement corrects a likely misconception?`, [stage.boundary, "More leakage improves evaluation", "Prediction always changes weights"], stage.boundary], [stage.completion.prompt, stage.completion.options, stage.completion.correct], [`Where does ${stage.label.toLowerCase()} belong?`, [`Before the next pipeline stage`, "After deleting the dataset", "Outside the ML pipeline"], "Before the next pipeline stage"]],
    review: [[`Which result summarizes this stage?`, [stage.result, "A user profile", "A stylesheet"], stage.result], [`Would the same principle transfer to another dataset?`, ["Yes, with task-appropriate inputs", "No, never", "Only without labels"], "Yes, with task-appropriate inputs"], [`Which boundary must remain true?`, [stage.boundary, "Use test answers while fitting", "Skip evaluation"], stage.boundary]],
  };
  const labels: Record<Exclude<InstructionalStep, "implement">, string[]> = { activate: ["Concept identification", "Output prediction", "Code explanation"], connect: ["Concept matching", "Comparison", "Analogy mapping"], learn: ["Transfer or new", "Difference", "Concept boundary"], practice: ["Misconception check", "Find the issue", "Pipeline ordering"], review: ["Concept summary", "New scenario", "Final checkpoint"] };
  return content[step].map(([prompt, options, answer], index) => make(index, labels[step][index], prompt, options, answer));
}

export function additionalQuestionBank(task: AdditionalTask, stage: StageSpec): Record<InstructionalStep, QuestionItem[]> {
  return Object.fromEntries((["activate", "connect", "implement", "learn", "practice", "review"] as InstructionalStep[]).map((step) => [step, questions(task, stage, step)])) as Record<InstructionalStep, QuestionItem[]>;
}
